"""Posts generated by the users"""
from models import BaseModel, Workout

from datetime import datetime
from playhouse.postgres_ext import (CharField, PrimaryKeyField, 
                                    JSONField, DateTimeField, ForeignKeyField)


class Post(BaseModel):
    id = PrimaryKeyField()
    comments = JSONField(default=[])
    photo = CharField(null=True)
    caption = CharField(null=True)
    date = DateTimeField(default=datetime.now())
    original_workout = ForeignKeyField(Workout)

    class Meta:
        index = ('post', 'original_workout')
