"""Posts generated by the users"""
from models import BaseModel
from datetime import datetime
from playhouse.postgres_ext import (CharField, PrimaryKeyField, 
                                    JSONField, DateTimeField)


class Post(BaseModel):
    id = PrimaryKeyField()
    comments = JSONField(default=[])
    photo = CharField(null=True)
    caption = CharField(null=True)
    date = DateTimeField(default=datetime.now())
