"""Workouts generated by the users"""
from models import BaseModel
from datetime import datetime
from playhouse.postgres_ext import (CharField, PrimaryKeyField, 
                                    DateTimeField, JSONField)


class Workout(BaseModel):
    id = PrimaryKeyField()
    name = CharField(null=False)
    category = CharField()
    start_time = DateTimeField(default=datetime.now())
    end_time = DateTimeField()
    creator = CharField(null=False)
    exercises = JSONField(default=[])
